site_name: Crucible Documentation
site_description: "CRUCIBLE is an open-source application framework for creating and managing virtual environments and events."
site_author: "Crucible Team"
copyright: >
  Copyright &copy; 2025-2026 Carnegie Mellon University. All rights reserved.
extra_css:
  - https://fonts.googleapis.com/icon?family=Material+Icons
  - stylesheets/extra.css
theme:
  name: material
  custom_dir: material/overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - toc.integrate
    - content.code.copy
    - content.code.annotate
    - content.external_links
  logo: assets/img/home/cruciblelogo.svg
  favicon: assets/img/home/cruciblelogo.svg
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: red

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: red
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - admonition
  - attr_list
extra:
  features:
    - content.icons
  social:
    - icon: material/message-question
      link: https://github.com/cmu-sei/Crucible/issues/new?template=question.md
      name: Ask a Question
    - icon: fontawesome/solid/bug
      link: https://github.com/cmu-sei/crucible/issues/new?template=bug_report.md
      name: Report a Problem
    - icon: material/lightbulb-on
      link: https://github.com/cmu-sei/crucible/issues/new?template=feature_request.md
      name: Request a Feature
    - icon: fontawesome/regular/comments
      link: https://github.com/cmu-sei/crucible/discussions
      name: Community Discussions
    - icon: fontawesome/brands/github
      link: https://github.com/cmu-sei/crucible
      name: cmu-sei/Crucible on Github
    - icon: fontawesome/regular/envelope
      link: mailto:info@sei.cmu.edu?subject=Crucible%20Feedback
      name: Email Crucible Team
    - icon: fontawesome/solid/house
      link: https://www.sei.cmu.edu/
      name: Software Engineering Institute
nav:
  - Home: index.md
  - Getting Started: getting-started/index.md
  - Installation Guide: install/index.md
  - Core Application Guides:
      - Landing: landing/index.md
      - Player: player/index.md
      - Caster: caster/index.md
      - Steamfitter: steamfitter/index.md
      - Alloy: alloy/index.md
      - TopoMojo: topomojo/index.md
      - Gameboard: gameboard/index.md
      - Blueprint: blueprint/index.md
      - CITE: cite/index.md
      - Gallery: gallery/index.md
  - Role-Based Guides:
      - Overview: roles/index.md
      - Permissions: roles/permissions.md
      - Infrastructure Administrator:
          - Overview: roles/administrator/index.md
          - Quick Start Guide: roles/administrator/quick-start.md
          - Deployment: roles/administrator/deployment/index.md
          - Security: roles/administrator/security/index.md
          - System Operations: roles/administrator/system-operations/index.md
          - User Management: roles/administrator/user-management/index.md
          - Troubleshooting: roles/administrator/troubleshooting/index.md
      - Range Builder:
          - Overview: roles/range-builder/index.md
          - Quick Start Guide: roles/range-builder/quick-start.md
          - Infrastructure Development: roles/range-builder/infrastructure/index.md
          - Scenario Development: roles/range-builder/scenarios/index.md
          - Assessment: roles/range-builder/assessment/index.md
      - Instructor:
          - Overview: roles/instructor/index.md
      - Participant:
          - Overview: roles/participant/index.md
  - Tutorials:
      - Overview: tutorials/index.md
      - ODX consumed via Moodle: tutorials/crucible-odx-moodle/index.md
      - TopoMojo Challenge: tutorials/topomojo-challenge/index.md
      - Games Within Gameboard: tutorials/gameboard-build/index.md
  - 3rd-Party Integrations: integrations/index.md

repo_url: "https://github.com/cmu-sei/crucible"
repo_name: "cmu-sei/Crucible"
