site_name: Crucible Documentation
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  custom_dir: material/overrides
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - toc.integrate
  logo: assets/img/crucible-icon-c-alpha.svg
  favicon: assets/img/crucible-icon-c-alpha.svg
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: red

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: red
nav:
  - Home: index.md
  - Player: player/index.md
  - Caster: caster/index.md
  - Steamfitter: steamfitter/index.md
  - Alloy: alloy/index.md
  - Blueprint: blueprint/index.md
  - CITE: cite/index.md
  - Gallery:
    - gallery/index.md
    - Archive:
      - gallery/archive/index.md
    - Wall:
      - gallery/wall/index.md
